### PR TITLE
Adds continuelist addon. Closes #21

### LINKED ISSUE #21: continuelist addon
It would be nice if you could include the continuelist addon from
http://codemirror.net/addon/edit/continuelist.js

### PR DESCRIPTION
**Pull request by jbrooksuk**

### CODE REVIEW

**Comment by jbrooksuk** [comment]
@jbt ping! :)

**Comment by jbt** [comment]
Sorry sorry yep I'll sort this asap. Super busy but if I don't do it sometime today then feel free to prod me again

**Comment by jbrooksuk** [comment]
Oh no problem :) I'd seen you comment on a few things and didn't know if you'd missed the PR.

**Comment by jbt** [comment]
tada!

**Comment by jbrooksuk** [comment]
Awesome :)

**Pull request merged**
